global:
  pull_policy: "IfNotPresent"
  dynamicVolumes:
  - name: loki
    host_path: /loki

loki:
  port: 3100
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  storage_size: 10Gi
