---
global:
  default_admin_limits_mem: "50Mi"
  default_admin_requests_mem: "50Mi"
  # HTTP_PROXY for all pods, defaults to squid proxy if not overwritten
  http_proxy: "http://squid-proxy-service.admin.svc.cluster.local:3128"
  # HTTPS_PROXY for all pods, defaults to squid proxy if not overwritten
  https_proxy: "http://squid-proxy-service.admin.svc.cluster.local:3128"