apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.alloy.name }}
  namespace: services
spec:
  ports:
  - port: {{ .Values.alloy.port }}
    targetPort: http
    name: http
  selector:
    app: {{ .Values.alloy.name }}