---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-serviceaccount
  namespace:  "{{ .Values.global.services_namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: "{{ .Values.global.services_namespace }}"
  name: pod-watcher-promtail
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes", "nodes/proxy", "services", "endpoints"]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-watcher-promtail-binding
  namespace: "{{ .Values.global.services_namespace }}"
subjects:
- kind: ServiceAccount
  name: promtail-serviceaccount
  namespace: "{{ .Values.global.services_namespace }}"
roleRef:
  kind: ClusterRole
  name: pod-watcher-promtail
  apiGroup: rbac.authorization.k8s.io
