apiVersion: v1
kind: ConfigMap
metadata:
  name: access-information-interface-config
  namespace: "{{ .Values.global.services_namespace }}"
data:
  initial_rights.json: | # This is the initial rights that will be created
    [
      {
        "name": "edit_project",
        "description": "Add or remove users from project",
        "claim_key": "kaapana",
        "claim_value": "edit_project"
      },
      {
        "name": "edit_user",
        "description": "Edit user rights within project",
        "claim_key": "kaapana",
        "claim_value": "edit_user"
      },
      {
        "name": "dev_tools",
        "description": "Get access to dev tools and APIs",
        "claim_key": "kaapana",
        "claim_value": "dev_tools"
      },
      {
        "name": "workflows",
        "description": "Rights to start a workflow, see workflow status and logs",
        "claim_key": "kaapana",
        "claim_value": "workflows"
      },
      {
        "name": "delete_data",
        "description": "Delete data from platform",
        "claim_key": "kaapana",
        "claim_value": "delete_data"
      },
      {
        "name": "opensearch_read",
        "description": "Read opensearch index data per project",
        "claim_key": "opensearch",
        "claim_value": "read_project"
      },
      {
        "name": "opensearch_admin",
        "description": "Opensearch admin role for the project index",
        "claim_key": "opensearch",
        "claim_value": "admin_project"
      },
      {
        "name": "minio_read",
        "description": "Read policy for the project bucket in minio",
        "claim_key": "policy",
        "claim_value": "read_project"
      },
      {
        "name": "minio_admin",
        "description": "Admin policy for the project bucket in minio",
        "claim_key": "policy",
        "claim_value": "admin_project"
      }
    ]
  initial_roles.json: | # This is the initial roles that will be created
    [
      {
        "name": "admin",
        "description": "Admin role"
      },
      {
        "name": "read-only",
        "description": "Read only role"
      },
      {
        "name": "project-pi",
        "description": "Project PI role"
      },
      {
        "name": "project-member",
        "description": "Project member role"
      }
    ]
  initial_projects.json: | # This is the initial admin project that will be created
    [
      {
        "name": "admin",
        "description": "Initial admin project"
      }
    ]
  initial_roles_rights_mapping.json: | # This is the mapping of roles to rights
    [
      {
        "role": "admin",
        "rights": ["edit_project", "edit_user", "dev_tools", "workflows", "opensearch_admin", "minio_admin", "delete_data"]
      },
      {
        "role": "read-only",
        "rights": ["opensearch_read","minio_read"]
      },
      {
        "role": "project-pi",
        "rights": ["edit_user", "workflows", "opensearch_admin", "minio_admin", "delete_data"]
      },
      {
        "role": "project-member",
        "rights": ["workflows", "opensearch_admin", "minio_admin"]
      }
    ]

  # Init User, Project and Role mapping will be done at a later stage (FastAPI lifespan init function) to dynamically incorporate the keycloak id.
