apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-egress
  namespace: {{ .Values.global.services_namespace }}
spec:
  podSelector: {}  # Applies to all pods in the namespace
  policyTypes:
  - Egress
  egress:
    {{- range .Values.global.internalCidrs }}
    - to:
      - ipBlock:
          cidr: {{ . | quote }}
    {{- end }}
