apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: squid-proxy-allow-egress
  namespace: "{{ .Values.global.admin_namespace  }}"
  labels:
    app.kubernetes.io/name: squid-proxy
spec:
  podSelector:
    matchLabels:
        app.kubernetes.io/name: squid-proxy
  policyTypes:
  - Egress
  egress:
  - {} # Allow all egress