apiVersion: v1
kind: Service
metadata:
  name: squid-proxy-service
  namespace: "{{ .Values.global.admin_namespace  }}"
  labels:
    app.kubernetes.io/name: squid-proxy
spec:
  ports:
  - name: squid-http-proxy
    protocol: TCP
    port: 3128
    targetPort: 3128
  selector:
    app.kubernetes.io/name: squid-proxy